### ISSUE TITLE
询问下使用方法

### ISSUE THREAD

**Issue by xswl-yyds** [YouCanAi/LyricsGetterExt#8]
你好，请问下这个必须搭配最新版的状态栏歌词使用吗？我的目前是旧版的5.4.1，使用了lyrics getter，但是使用ext之后没有反应，不清楚是不是旧版的问题。新版在我手机上使用情况不是很好
麻烦了

**Comment by molian313** [comment]
我用的最新版也没作用，不知道为啥

**Comment by J1mmyBoy** [comment]
打开spotify的设备广播就可以了

**Comment by xswl-yyds** [comment]
你好，我这边不知道为啥，现在没打开广播状态也可以正常使用😂想问下youtube music可以使用这个吗？
之前我先在youtube music里面放歌，再切换到spotify，插件居然也可以用，也可以显示歌词，但是生效次数很少

________________________________
发件人: Jimmy仔 ***@***.***>
发送时间: 星期四, 十二月 14, 2023 6:43:22 下午
收件人: YouCanAi/LyricsGetterExt ***@***.***>
抄送: xswl-yyds ***@***.***>; Author ***@***.***>
主题: Re: [YouCanAi/LyricsGetterExt] 询问下使用方法 (Issue #8)


打开spotify的设备广播就可以了

**Comment by J1mmyBoy** [comment]
spotify没开广播用不了，我用的youtube music revanced不行

**Comment by xswl-yyds** [comment]
> spotify没开广播用不了，我用的youtube music revanced不行

我这边spotify没看广播也可以😂
你说的youtube music revanced是啥意思啊？😂

**Comment by J1mmyBoy** [comment]
> > spotify没开广播用不了，我用的youtube music revanced不行
> 
> 我这边spotify没看广播也可以😂 你说的youtube music revanced是啥意思啊？😂

破解版

**Comment by YouCanAi** [comment]
> 你好，请问下这个必须搭配最新版的状态栏歌词使用吗？我的目前是旧版的5.4.1，使用了lyrics getter，但是使用ext之后没有反应，不清楚是不是旧版的问题。新版在我手机上使用情况不是很好 麻烦了

可能是由于你使用了最新版的ext而最新版的ext所支持的Lyrics Getter Api与您设备上的Lyrics Getter所支持的API不匹配，这边的建议是可以尝试[安装较旧版本的ext](https://github.com/YouCanAi/LyricsGetterExt/releases/tag/1.0.6)
